#installing nginx
- name: Installing nginx
  hostname: mongodb
  task:
    - name: installing nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
    -name: starting nginx
     ansible.builtin.service:
      name: nginx
      state: estarted 