- name: variables from files
  hosts: localhost #managing the ansible server itself
  vars_files:
  - variable_list.yaml
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "We are learning, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"